// src/constants/geoData.js

export const KARNATAKA_DISTRICTS = [
  "Bagalkot",
  "Ballari",
  "Belagavi",
  "Bengaluru Rural",
  "Bengaluru Urban",
  "Bidar",
  "Chamarajanagar",
  "Chikkaballapur",
  "Chikkamagaluru",
  "Chitradurga",
  "Dakshina Kannada",
  "Davanagere",
  "Dharwad",
  "Gadag",
  "Hassan",
  "Haveri",
  "Kalaburagi",
  "Kodagu",
  "Kolar",
  "Koppal",
  "Mandya",
  "Mysuru",
  "Raichur",
  "Ramanagara",
  "Shivamogga",
  "Tumakuru",
  "Udupi",
  "Uttara Kannada",
  "Vijayanagara",
  "Vijayapura",
  "Virtual / Online",
  "Yadgir",
];

// Comprehensive district & tech hub directory (alphabet-indexed)
export const ALL_DISTRICTS = [
  // A - Prominent Indian collegiate tech districts & hubs
  "Agra",
  "Ahmedabad",
  "Alappuzha",
  "Amritsar",
  "Anantapur",
  // B
  "Bagalkot",
  "Ballari",
  "Belagavi",
  "Bengaluru Rural",
  "Bengaluru Urban",
  "Bhopal",
  "Bhubaneswar",
  "Bidar",
  // C
  "Chamarajanagar",
  "Chandigarh",
  "Chennai",
  "Chikkaballapur",
  "Chikkamagaluru",
  "Chitradurga",
  "Coimbatore",
  // D
  "Dakshina Kannada",
  "Davanagere",
  "Delhi NCR",
  "Dharwad",
  // E & G
  "Ernakulam",
  "Gadag",
  "Gurugram",
  "Guwahati",
  // H
  "Hassan",
  "Haveri",
  "Hyderabad",
  // I, J, K
  "Indore",
  "Jaipur",
  "Kalaburagi",
  "Kochi",
  "Kodagu",
  "Kolar",
  "Kolkata",
  "Koppal",
  "Kozhikode",
  // L, M
  "Lucknow",
  "Mandya",
  "Mangaluru",
  "Mumbai",
  "Mysuru",
  // N, P
  "Nagpur",
  "Noida",
  "Patna",
  "Pune",
  // R, S
  "Raichur",
  "Raipur",
  "Ramanagara",
  "Ranchi",
  "Shivamogga",
  "Surat",
  // T, U, V, W, Y
  "Thiruvananthapuram",
  "Tumakuru",
  "Udupi",
  "Uttara Kannada",
  "Vadodara",
  "Varanasi",
  "Vijayapura",
  "Vijayanagara",
  "Visakhapatnam",
  "Virtual / Online",
  "Yadgir",
];

export const ALL_INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Karnataka / Virtual",
];

export default {
  KARNATAKA_DISTRICTS,
  ALL_DISTRICTS,
  ALL_INDIAN_STATES,
};
