// src/constants/geoData.js

// Official 31 Karnataka Districts (+ Virtual)
export const KARNATAKA_DISTRICTS = [
  "Bagalkot",
  "Ballari",
  "Belagavi",
  "Bengaluru Rural",
  "Bengaluru Urban",
  "Bidar",
  "Chamarajanagar",
  "Chikkaballapur",
  "Chikkamagaluru",
  "Chitradurga",
  "Dakshina Kannada",
  "Davanagere",
  "Dharwad",
  "Gadag",
  "Hassan",
  "Haveri",
  "Kalaburagi",
  "Kodagu",
  "Kolar",
  "Koppal",
  "Mandya",
  "Mysuru",
  "Raichur",
  "Ramanagara",
  "Shivamogga",
  "Tumakuru",
  "Udupi",
  "Uttara Kannada",
  "Vijayanagara",
  "Vijayapura",
  "Virtual / Online",
  "Yadgir",
];

// District mapping strictly grouped by State
export const STATE_DISTRICTS_MAP = {
  "Karnataka": KARNATAKA_DISTRICTS,
  "Karnataka / Virtual": ["Virtual / Online", ...KARNATAKA_DISTRICTS],
  "Delhi": [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "South Delhi",
    "West Delhi",
  ],
  "Maharashtra": [
    "Aurangabad",
    "Mumbai",
    "Nagpur",
    "Nashik",
    "Pune",
    "Thane",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Salem",
    "Tiruchirappalli",
  ],
  "Telangana": [
    "Hyderabad",
    "Karimnagar",
    "Nizamabad",
    "Warangal",
  ],
  "Gujarat": [
    "Ahmedabad",
    "Gandhinagar",
    "Rajkot",
    "Surat",
    "Vadodara",
  ],
  "Kerala": [
    "Alappuzha",
    "Kochi",
    "Kozhikode",
    "Thiruvananthapuram",
    "Thrissur",
  ],
  "Andhra Pradesh": [
    "Anantapur",
    "Guntur",
    "Tirupati",
    "Vijayawada",
    "Visakhapatnam",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Kanpur",
    "Lucknow",
    "Noida",
    "Prayagraj",
    "Varanasi",
  ],
  "West Bengal": [
    "Durgapur",
    "Howrah",
    "Kolkata",
    "Siliguri",
  ],
  "Punjab": [
    "Amritsar",
    "Jalandhar",
    "Ludhiana",
    "Mohali",
    "Patiala",
  ],
  "Haryana": [
    "Ambala",
    "Faridabad",
    "Gurugram",
    "Panipat",
  ],
  "Rajasthan": [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Udaipur",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Gwalior",
    "Indore",
    "Jabalpur",
  ],
  "Bihar": [
    "Bhagalpur",
    "Gaya",
    "Muzaffarpur",
    "Patna",
  ],
  "Odisha": [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
  ],
  "Assam": [
    "Dibrugarh",
    "Guwahati",
    "Silchar",
  ],
};

export const ALL_INDIAN_STATES = [
  "Karnataka",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Karnataka / Virtual",
];

export default {
  KARNATAKA_DISTRICTS,
  STATE_DISTRICTS_MAP,
  ALL_INDIAN_STATES,
};
